# fly.toml app configuration file generated for django-crispy-formset-modal on 2023-05-18T11:10:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-crispy-formset-modal"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[build]
  dockerfile = ".deployment/Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
